---
- name: Create Docker network
  docker_network:
    name: ci-net
    state: present

- name: Run Jenkins service
  become: yes
  become_user: ubuntu
  include_tasks: docker.yml
  vars:
    directory: "{{ repo_dir }}/docker/{{ item }}"
  with_items:
    - jenkins
    - traefik
